languageCode = "en"
languageName = "English"
weight = 1
title = "NE"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/EndOfDay2.png"
  description = "Personal website of Nicholas Ee."

[params.author]
  name = "Nicholas Ee"
  headline = "UX Designer | Game Designer"
  bio = "I'm a UX designer and game designer based in Singapore. I design, code and write things."